actions/init.js
content-script.js
events/dispatcher.js
events/listeners.js
manifest.json
models/icon.js
models/skip.js
models/slider/slider-controls.js
models/slider/slider.js
models/snip/snip.js
observers/current-time.js
observers/now-playing.js
observers/track-list.js
stores/cache.js
stores/data.js
styles.css

Allow User to block/unblock a track from anywhere - queue, album tracklist, playllist, and artist page. Below are images of a blocked/unblocked track and the respective tooltip that appears when hovering over the block icon.
---
---
---
closes #2

Feat: Toggle Track Block/UnBlock

---

models/skip.js
models/snip/snip.js
models/video.js
observers/current-time.js

Fixes issue where a "normal" track starts playing and then get reset back to start point causing a jerky playback.
closes: #11

Fix: Jerky Playback of Non-Snip & Non-Skip Tracks

---

actions/init.js
actions/main.js
background.js
manifest.json
models/icon.js
observers/now-playing.js
observers/track-list.js

Toggling Action Icon should now toggle on/off ALL currently implemented features - snips, blocked tracks, display of settings icon.
Also bumped version to 1.1.1 for release to Chrome Store.
closes #12

Fix: Action Icon 

---

components/header.js

Updated X with svg icon (issue #15)

---

components/header.js
components/slider.js
models/skip.js
styles.css

changes in styles.css and components/slider
Added slider-container
The thumbs and slider color will change when hovering slider-components.
closes #18

Update Slider to Closer Resemble Spotify UI

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Creates issue and feature request template files for this project.
Closes #27

Create issue report template

---

components/buttons.js
models/snip/snip.js
styles.css

Fix: Vertical Alignment of Time & Buttons Text

---

models/track-list.js

Fix bug where Queue tracklists icons are not triggered on click.
closes #33

Fix: Tracklist Icon Events

---

styles.css

Closes #29 
**_Add Cursor Pointer to Settings Icon to signify it is Clickable._**

Add Cursor Pointer to Settings Icon

---

models/icon.js

Closes #30 
**Add** `role` **and** `aria-label` **to Settings Icon in icon.js**

Add aria-label to Settings Icon

---

styles.css

Fix Skip Icon arial label positioning

---

.github/workflows/release.yml

Release Action:
1. Bump version in manifest.version based on PR commit title semver keywords/regex:
- "feat:*" minor bump
- "*!:*" major bump
- default (fix, chore, doc, ci, etc) minor bump
2. Commit, tag and push bump change commit. 
3. Create release artifact
closes #5

ci: create release.yml action

---

.github/workflows/release.yml

Updates to Daily Release
- use schedule (set at 09:30 UTC daily)
- only run on develop branch
- use semantic release action instead of custom

ci: update release.yml to schedule

---

.github/workflows/deploy.yml

Add GH Action to create zipped package. Afterwards, upload and publish (after Google's review) the package.
closes: #52

ci: create deploy.yml

---

.allcontributorsrc
.github/workflows/release.yml
readme.md

Sets up all-contributors configuration
closes #57

docs: setup all-contributors

---

observers/current-time.js

fix: snip set as shared even when not shared

---

observers/current-time.js

fix: snip looping back to start when repeat 1 set

---

events/listeners.js
models/slider/slider.js
models/snip/snip.js
observers/current-time.js

fix: allow endtime edit w/o jump to next track

---

README.md

docs: flesh out readme with project details

---

actions/init.js
models/video.js

fix: speed toggle on/off on extension init

---

README.md

docs: update README with badges and features

---

README.md

docs: add install links directing to Chrome Web Store in readme

---

.github/workflows/release.yml
chrome/manifest.json

fix: chrome manifest.json removed during release workflow

---

README.md

docs: update version badge in README

---

.github/workflows/release.yml
.gitignore
package.json
pnpm-lock.yaml
rollup.config.js
src/content-script.js
src/manifest.chrome.json
src/manifest.firefox.json
src/utils/state.js

feat: create dev builds with hmr

---

.all-contributorsrc

docs: fix .all-contributorsrc format

---

src/components/header.js
src/components/seek/seek-buttons.js
src/components/seek/seek-controls.js
src/components/seek/seek-icon.js
src/components/seek/seek-inputs.js
src/components/seek/seek-toggler.js
src/data/current.js
src/events/listeners.js
src/models/chorus.js
src/models/icon.js
src/models/seek/seek-controller.js
src/models/seek/seek-icon.js
src/models/seek/seek.js
src/models/speed/speed.js
src/observers/current-time.js
src/observers/now-playing.js
src/styles.css
src/utils/song.js

feat: custom seeking fast-forward and rewind

---

src/components/seek/seek-icon.js
src/models/seek/seek-controller.js
src/models/seek/seek-icon.js
src/stores/data.js

fix: seek icon console error & label misupdate

---

src/background.js
src/manifest.chrome.json
src/manifest.firefox.json

feat: setup shortkey commands for player controls

---

src/components/icons/icon.js
src/models/icon.js
src/models/snip/current-snip.js
src/models/tracklist/skip-icon.js
src/models/tracklist/snip-icon.js
src/styles.css

refactor: extract icon into component

---

src/components/seek/seek-buttons.js
src/components/seek/seek-inputs.js
src/components/seek/seek-toggler.js
src/components/snip/snip-buttons.js
src/components/snip/snip-labels.js
src/components/snip/snip-slider.js
src/components/speed/speed-buttons.js
src/components/speed/speed-toggler.js
src/components/text-button.js
src/data/current.js
src/models/speed/speed.js
src/styles.css

refactor: components + address TODOs

---

src/events/listeners/action-listeners.js

fix: import missing .js extension

---

src/actions/init.js
src/data/song-state.js
src/models/now-playing-icons.js
src/models/snip/current-snip.js
src/models/snip/snip.js
src/models/snip/track-snip.js
src/models/tracklist/track-list.js
src/models/tracklist/tracklist-icon.js
src/models/video/video-override.js
src/models/video/video.js
src/observers/current-time/song-tracker.js
src/observers/now-playing.js
src/observers/track-list.js
src/utils/higlight.js
src/utils/song.js

- Refactor highlight feature
- Address issues relating to currently playing track seek, skip, and snip features
- Additional refactors for readability (making progress)
closes #133

feat: highlight snips

---

src/models/video/video.js
src/observers/current-time/song-tracker.js

fix: track changes due to skip and snip times

---

src/components/snip/snip-labels.js
src/events/listeners/listeners.js
src/models/snip/snip.js
src/observers/song-tracker.js

feat: allow unsaved start & time in share url

---

src/actions/init.js
src/observers/song-tracker.js

fix: SongTracker volume changes

---

src/data/song-state.js
src/observers/song-tracker.js
src/utils/request.js

fix: set default trackId to id from share url path

---

src/background.js
src/observers/song-tracker.js

fix: update send headers listener for firefox to retrieve auth

---

.github/workflows/release.yml

docs: zipped files includes temp folders

---

src/models/snip/current-snip.js
src/models/snip/snip.js
src/models/snip/track-snip.js

fix: update settings highlight on snip deletion

---

src/observers/song-tracker.js

fix: set volume unMute value to volume bar percent

---

src/background.js
src/manifest.chrome.json
src/manifest.firefox.json
src/observers/song-tracker.js
src/popup/index.html
src/popup/index.js
src/popup/ui.js
src/stores/data.js

Addresses:
1. non-scrolling artists and title texts in popup ui greater than width of their container
2. empty image on first install or no active tab or track

fix: short command toggle extension on/off

---

src/background.js
src/models/now-playing-icons.js
src/utils/higlight.js

Addresses:
1. shortcut keys commands not executing
2. current track skip not highlighting skipped song in tracklist

fix: current track block highlights icon in tracklist

---

src/actions/init.js
src/models/app.js
src/models/now-playing-icons.js
src/models/seek/seek-icon.js
src/styles.css

1. Seek + Setting Icons visible when extension is turned off
2. Seek icons missing aria labels

fix: seek icons visibility on toggle + aria labels

---

src/background.js
src/components/artist-disco.js
src/content-script.js
src/manifest.chrome.json
src/manifest.firefox.json
src/models/alert.js
src/models/app.js
src/observers/artist-disco.js
src/observers/song-tracker.js
src/popup/index.js
src/popup/toggle.js
src/services/artist-disco.js
src/services/player.js
src/styles.css
src/utils/messaging.js
src/utils/request.js
src/utils/state.js

PR includes:
1. Work with setting up artist discography functionality
2. Make Alert#displayAlert more robust - accept duration, type, and message args
3. Fix messaging b/t page, content and background scripts
4. Make request and messaging utils more robust
closes #160

feat: artist discography

---

package.json
src/background.js
src/manifest.chrome.json
src/manifest.firefox.json

fix: create artist disco key mistype

---

src/stores/cache.js

fix: retrieving store values causes update

---

.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/sync.yml

docs: separate out publish workflow

---

src/components/icons/icon.js
src/models/app.js
src/models/heart-icon.js
src/models/tooltip.js
src/models/tracklist/heart-icon.js
src/models/tracklist/track-list.js
src/models/tracklist/tracklist-icon.js
src/styles.css
src/utils/tooltip.js

fix: generalize tooltip ui

---

src/App.svelte
src/entrypoints/background.ts
src/entrypoints/popup/App.svelte
src/lib/components/SupportAlert.svelte
src/lib/components/SupportDialog.svelte
src/lib/components/views/Support.svelte
src/lib/observers/track.ts
src/lib/stores/settings.ts
src/lib/stores/supporter.ts
src/lib/utils/command.ts
src/lib/utils/notifications.ts
wxt.config.ts

Setup track notification triggered by track change or shortkey command.
closes #237

FEAT: setup notification util

---

package.json
src/lib/components/AudioEffectInputs.svelte
src/lib/components/PlaybackInput.svelte
src/lib/components/SettingsSwitch.svelte
src/lib/media/media-element.ts
src/lib/media/media-override.ts
src/lib/stores/playback.ts

- Add preserves_pitch property to playback rate field
- add switch to toggle preserves_pitch property
- remove supporter lock from SettingsSwitch
- increase button width/height in speed & fx|eq inputs

feat: add preserve pitch field for playback rate

---

src/App.svelte
src/entrypoints/background.ts
src/entrypoints/chorus.content.ts
src/entrypoints/router.ts
src/lib/api/request.ts
src/lib/api/services/new-releases.ts
src/lib/api/services/player.ts
src/lib/api/services/queue.ts
src/lib/api/services/track.ts
src/lib/components/NewReleasesDialog.svelte
src/lib/components/NewReleasesHeader.svelte
src/lib/components/NewReleasesIcon.svelte
src/lib/components/ScrollingText.svelte
src/lib/components/SupportAlert.svelte
src/lib/components/Tippy.svelte
src/lib/components/ui/tooltip/tooltip-content.svelte
src/lib/components/views/NewReleases.svelte
src/lib/media/media-element.ts
src/lib/stores/new-releases.ts
src/lib/utils/click-outside.ts
src/lib/utils/groupings.ts
src/lib/utils/selectors.ts
src/lib/utils/store-utils.ts
src/lib/utils/time.ts
tailwind.config.ts
wxt.config.ts

feat: new releases
